### ISSUE TITLE
Error Building on OS X 10.8

### ISSUE THREAD

**Issue by theory** [citusdata/json_fdw#1]
Just tried to build on OS X Mountain Lion 10.8.5 with cmake 2.8.12 and yajl 2.0.1 but got some errors:

```
> make
gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv  -I. -I. -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_XOPEN_SOURCE -I/usr/local/include/libxml2  -I/usr/local/include  -c -o json_fdw.o json_fdw.c
json_fdw.c:656:52: error: invalid application of 'sizeof' to an incomplete type
      'HeapTupleHeaderData' (aka 'struct HeapTupleHeaderData')
  ...tupleWidth = MAXALIGN(baserel->width) + MAXALIGN(sizeof(HeapTupleHeaderData));
                                                      ^     ~~~~~~~~~~~~~~~~~~~~~
/usr/local/pgsql/include/server/c.h:540:53: note: expanded from macro 'MAXALIGN'
#define MAXALIGN(LEN)                   TYPEALIGN(MAXIMUM_ALIGNOF, (LEN))
                                                                    ^
/usr/local/pgsql/include/server/c.h:534:16: note: expanded from macro 'TYPEALIGN'
        (((intptr_t) (LEN) + ((ALIGNVAL) - 1)) & ~((intptr_t) ((ALIGNVAL) - 1)))
                      ^
/usr/local/pgsql/include/server/access/htup.h:21:16: note: forward declaration of
      'struct HeapTupleHeaderData'
typedef struct HeapTupleHeaderData HeapTupleHeaderData;
               ^
json_fdw.c:1479:35: warning: implicit declaration of function 'heap_form_tuple' is invalid
      in C99 [-Wimplicit-function-declaration]
                        sampleRows[sampleRowCount++] = heap_form_tuple(tupleDescriptor, 
                                                       ^
json_fdw.c:1479:33: warning: incompatible integer to pointer conversion assigning to
      'HeapTuple' (aka 'struct HeapTupleData *') from 'int' [-Wint-conversion]
                        sampleRows[sampleRowCount++] = heap_form_tuple(tupleDescriptor, 
                                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
json_fdw.c:1506:5: warning: implicit declaration of function 'heap_freetuple' is invalid
      in C99 [-Wimplicit-function-declaration]
                                heap_freetuple(sampleRows[rowIndex]);
                                ^
json_fdw.c:1507:26: warning: incompatible integer to pointer conversion assigning to
      'HeapTuple' (aka 'struct HeapTupleData *') from 'int' [-Wint-conversion]
                                sampleRows[rowIndex] = heap_form_tuple(tupleDescriptor,
                                                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 1 error generated.
make: *** [json_fdw.o] Error 1
```
